import { recipe } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";

type Props = { recipes: recipe[] };

// Fetch all recipes (in /pages/index.tsx)
export async function getStaticProps() {
  const recipes = await prisma.recipe.findMany();

  return {
    props: { recipes },
  };
}

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>lets create this fucking websites</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-900">
          Create <span className="text-purple-500">aaaarghhhh</span> App
        </h1>
        <p className="text-2xl text-gray-700">
          This stack uses: a lot of time and effort and we will never make it
        </p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-3 lg:w-2/3">
          {((props as Props).recipes as recipe[]).map((recipe) => (
            <div key={recipe.id}>
              <p>{recipe?.title}</p>
              <p>{recipe?.description}</p>
              <p>{recipe?.ingredients}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
